//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Club_Campestre.SVC_CatalogosMantenimientos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVC_CatalogosMantenimientos.ICatalogosMantenimientos")]
    public interface ICatalogosMantenimientos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogosMantenimientos/listarEstado", ReplyAction="http://tempuri.org/ICatalogosMantenimientos/listarEstadoResponse")]
        System.Data.DataTable listarEstado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogosMantenimientos/listarEstado", ReplyAction="http://tempuri.org/ICatalogosMantenimientos/listarEstadoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> listarEstadoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogosMantenimientosChannel : Club_Campestre.SVC_CatalogosMantenimientos.ICatalogosMantenimientos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogosMantenimientosClient : System.ServiceModel.ClientBase<Club_Campestre.SVC_CatalogosMantenimientos.ICatalogosMantenimientos>, Club_Campestre.SVC_CatalogosMantenimientos.ICatalogosMantenimientos {
        
        public CatalogosMantenimientosClient() {
        }
        
        public CatalogosMantenimientosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogosMantenimientosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogosMantenimientosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogosMantenimientosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable listarEstado() {
            return base.Channel.listarEstado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> listarEstadoAsync() {
            return base.Channel.listarEstadoAsync();
        }
    }
}
